const TOGGLE_LOADER = 'TOGGLE_LOADER';
const HIDE_LOADER = 'HIDE_LOADER';

const SET_USER = 'SET_USER';
const USER_LOGOUT = 'USER_LOGOUT';

const SET_THEME = 'SET_THEME';
const SET_LANGUAGE = 'SET_LANGUAGE';

export default {
  TOGGLE_LOADER,
  HIDE_LOADER,
  SET_USER,
  USER_LOGOUT,
  SET_THEME,
  SET_LANGUAGE,
};
